proceed_to_checkout_button= "//a[@title=\"Proceed to checkout\"]"
proceed_to_checkout_button_to_shipping= "//button[@name=\"processAddress\"]"
proceed_to_checkout_button_to_payment= "//button[@name=\"processCarrier\"]"
delivery_address_summary_text_area= "//h3[@class=\"page-subheading\"]"
invoice_address_summary_text_area= "//h3[@class=\"page-subheading\"]"
choose_a_delivery_address_button=  "//select[@id=\"id_address_delivery\"]"
your_delivery_address_text_area =  "//ul[@id=\"address_delivery\"]"
your_billing_address_text_area =  "//ul[@id=\"address_invoice\"]"
update_button =  "//a[@title=\"Update\"]"
city_text_area =  "//input[@id=\"city\"]"
submit_address_button =  "//button[@id=\"submitAddress\"]"
city_address_text_area = "//li[@class=\"address_city address_state_name address_postcode\"]"
shipping_info_text_area =  "//form[@id=\"form\"]"
shipping_agree_button =  "//input[@id=\"cgv\"]"
terms_of_service_alert_text_area = "//p[@class=\"fancybox-error\"]"
pay_by_bank_wire_button =  "//a[@class=\"bankwire\"]"
pay_by_bank_check_button = "//a[@class=\"cheque\"]"