your_personal_information_text_area = "//h3[@class=\"page-subheading\" and contains(text(), 'Your personal information')]"
mrs_selection = "//div[@id=\"uniform-id_gender2\"]"
firstname_area = "//input[@id=\"customer_firstname\"]"
lastname_area = "//input[@id=\"customer_lastname\"]"
password_area= "//input[@id=\"passwd\"]"
date_of_birth_selection_day= "//select[@id=\"days\"]"
button_30= "//*[contains(text(),'30')]"
date_of_birth_selection_month= "//select[@id=\"months\"]"
january= "//*[contains(text(),'January')]"
date_of_birth_selection_year= "//select[@id=\"years\"]"
button_1995= "//*[contains(text(),'1995')]"
newsletter_confirmation_selection= "//input[@id=\"newsletter\"]"
special_offers_confirmation_selection= "//input[@id=\"optin\"]"
address_firstname_area= "//input[@id=\"firstname\"]"
address_lastname_area= "//input[@id=\"lastname\"]"
address_company_area= "//input[@id=\"company\"]"
address_line_1_area= "//input[@id=\"address1\"]"
address_line_2_area= "//input[@id=\"address2\"]"
city_area= "//input[@id=\"city\"]"
state_selection= "//select[@id=\"id_state\"]"
Alabama_state= "//*[text()='Alabama']"
zip_postal_code_area= "//input[@id=\"postcode\"]"
country_selection= "//select[@name=\"id_country\"]"
additional_information_area= "//textarea[@name=\"other\"] "
home_phone_area= "//input[@name=\"phone\"]"
mobile_phone_area= "//input[@name=\"phone_mobile\"]"
register_button= "//button[@name=\"submitAccount\"]"
invalid_text_area_for_password= "//*[@id=\"center_column\"]/div/ol/li"
invalid_text_area_for_zipcode= "//*[@id=\"center_column\"]/div/ol/li"