product_list_row= "//ul[@class=\"product_list grid row\"]"
grid_structure_button= "//i[@class=\"icon-th-large\"]"
list_structure_button= "//i[@class=\"icon-th-list\"]"
grid_structure_list= "//ul[@class=\"product_list row grid\"]"
list_structure_list= "//ul[@class=\"product_list row list\"]"
faded_short_sleeve_t_shirt_orange_button= "//a[@id=\"color_1\"]"
faded_short_sleeve_t_shirt_blue_button= "//a[@id=\"color_2\"]"
color_blue_selected= "//a[@class='color_pick selected' and @title='Blue']"
color_orange_selected= "//a[@class='color_pick selected' and @title='Orange']"
more_button= "//a[@title=\"View\"]"
description_area= "//div[@itemprop=\"description\"]"
faded_t_shirt= "//*[@id=\"center_column\"]/ul/li"
add_wishlist_button= "//a[@class=\"addToWishlist wishlistProd_1\"]"
add_to_compare_button= "//a[@class=\"add_to_compare\"]"
add_to_cart_button= "//a[@title=\"Add to cart\"]"
add_to_cart_progress_is_succeeded_icon= "//i[@class=\"icon-ok\"]"
checked_add_to_compare_button= "//a[@class=\"add_to_compare checked\"]"
successfully_added_text_area= "//p[@class=\"fancybox-error\"]"
evening_dresses_filter_button= "//div[@id=\"uniform-layered_category_10\"]"
evening_dresses_filter_accepted= "//div[@id=\"enabled_filters\"]"
price_range= "//div[@style=\"left: 0%; width: 100%;\"]"
cart_button= "//a[@title=\"View my shopping cart\"]"
remove_from_cart_button= "//a[@title=\"Delete\"]"
