create_an_account_text_area = "//h3[@class=\"page-subheading\" and contains(text(), 'C')]"
email_text_area = "//input[@id=\"email_create\"]"
email_delete_button = "//div[@id=\"create_account_error\"]"
create_an_account_button = "//button[@id=\"SubmitCreate\"]"
invalid_email_address_text_area = "//div[@id=\"create_account_error\"]"
already_used_email_text_area = "//div[@id=\"create_account_error\"]"
already_registered_text_area = "//h3[@class=\"page-subheading\"]"
signin_email_area = "//input[@id=\"email\"]"
signin_password_area = "//input[@id=\"passwd\"]"
signin_button = "//button[@id=\"SubmitLogin\"]"
authentication_failed_text_area = "//*[@id=\"center_column\"]/div[1]/ol/li"
forgot_your_password_button = "//a[@href=\"http://automationpractice.com/index.php?controller=password\"]"
confirm_my_order_button = "//button[@type=\"submit\" or contains(text(), 'I confirm')]"
